#!/bin/bash

# This is a useless script. My AI just gives magic 8 ball answers to any question you ask it

echo "Welcome to myAI, ask me any yes or no question. "

read question

# Random number 
max=21
response=$(( RANDOM % max ))

case $response in
    1) echo "It is certain!";;
    2) echo "It is decidedly so.";;
    3) echo "Without a doubt";;
    4) echo "Yes definitely";;
    5) echo "You may rely on it";;
    6) echo "As I see it, yes";;
    7) echo "Most likely";;
    8) echo "Outlook good";;
    9) echo "Yes";;
    10) echo "Signs point to yes";;
    11) echo "Reply hazy, try again";;
    12) echo "Ask again later";;
    13) echo "Better not tell you";;
    14) echo "Cannot predict now";;
    15) echo "Concentrate and ask again";;
    16) echo "Don't count on it";;
    17) echo "My reply is no";;
    18) echo "My sources say no";;
    19) echo "Outlook not so good";;
    20) echo "Very doubtful";;
    *) echo "Invalid response number";;  # default case
esac
