#!/usr/bin/env python3
import random

# this is going to be an AI chat bot
# But it is actually just magic 8 ball responses 

print("Hello, welcome to myAI.")
question = input("Ask me any yes or no question. ")

response = random.randint(1,20)

match response:
    case 1:
        print("It is certain!")
    case 2:
        print("It is decidedly so.")
    case 3:
        print("Without a doubt")
    case 4:
        print("Yes definitely")
    case 5:
        print("You may rely on it")
    case 6:
        print("As I see it, yes")
    case 7:
        print("Most likely")
    case 8:
        print("Outlook good")
    case 9:
        print("Yes")
    case 10:
        print("Signs point to yes")
    case 11:
        print("Reply hazy, try again")
    case 12:
        print("Ask again later")
    case 13:
        print("Better not tell you")
    case 14:
        print("Cannot predict now")
    case 15:
        print("Concentrate and ask again")
    case 16:
        print("Don't count on it")
    case 17:
        print("My reply is no")
    case 18:
        print("My sources say no")
    case 19:
        print("Outlook not so good")
    case 20:
        print("Very doubtful")


